import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronLeft, ChevronRight, Settings2, Image as ImageIcon, Zap, Target, HelpCircle, Layers, ArrowRight, Activity, Search, AlertTriangle, Fingerprint, EyeOff, Scissors, RefreshCw, Wand2, GitMerge } from 'lucide-react';


// --- SLIDE 1: The Core Concept & PGM ---
const CoreConceptSlide = () => {
  const [thickness, setThickness] = useState(50);
  const [rotation, setRotation] = useState(0);
  const [slant, setSlant] = useState(0);

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto">
      <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center shrink-0">Latent Variable Models (LVMs)</h2>
      <p className="text-slate-600 mb-8 text-center max-w-2xl mx-auto shrink-0 text-sm md:text-base">
        Observed data <span className="font-mono font-bold text-green-600">x</span> is generated by hidden, underlying factors called latent variables <span className="font-mono font-bold text-purple-600">z</span>. We don't see <span className="font-mono font-bold text-purple-600">z</span>, but it dictates everything about <span className="font-mono font-bold text-green-600">x</span>.
      </p>

      <div className="flex flex-col lg:flex-row items-center justify-center gap-8 lg:gap-16 flex-grow">
        
        {/* The Graphical Model (PGM) */}
        <div className="bg-slate-50 p-6 rounded-2xl border-2 border-dashed border-slate-300 flex flex-col items-center relative shadow-sm w-full max-w-sm">
           <div className="absolute top-4 left-4 text-xs font-bold text-slate-400 uppercase tracking-widest">Probabilistic Graphical Model</div>
           
           {/* Prior p(z) */}
           <div className="mt-8 border border-slate-300 border-dotted p-6 rounded-xl relative flex flex-col items-center w-full bg-white/50">
             <div className="absolute -top-3 left-4 bg-slate-50 px-2 text-xs font-semibold text-slate-500">Prior p(z)</div>
             <div className="w-20 h-20 bg-purple-100 border-4 border-purple-400 rounded-full flex flex-col items-center justify-center shadow-md relative z-10">
               <span className="text-2xl font-bold text-purple-600 font-mono">z</span>
             </div>
           </div>

           {/* Arrow */}
           <div className="flex flex-col items-center my-2">
             <div className="h-12 w-1 bg-slate-300"></div>
             <div className="w-0 h-0 border-l-[6px] border-l-transparent border-r-[6px] border-r-transparent border-t-[8px] border-t-slate-400"></div>
             <div className="absolute top-[55%] ml-32 text-xs font-semibold text-slate-500 bg-slate-50 px-1">Likelihood p(x|z)</div>
           </div>

           {/* Observed x */}
           <div className="w-20 h-20 bg-green-100 border-4 border-green-400 rounded-full flex flex-col items-center justify-center shadow-md relative z-10">
             <span className="text-2xl font-bold text-green-600 font-mono">x</span>
           </div>
           <div className="absolute bottom-4 left-4 bg-slate-400 text-white text-xs font-bold px-2 py-1 rounded">Observed</div>
        </div>

        {/* Interactive Example */}
        <div className="bg-white p-6 rounded-2xl shadow-xl border border-slate-100 flex flex-col w-full max-w-md">
          <h3 className="text-lg font-bold text-slate-700 mb-4 text-center border-b pb-2">Interactive Example: Handwritten Digit</h3>
          
          <div className="flex gap-6 items-center">
            {/* The Latent Space Sliders (z) */}
            <div className="flex-1 flex flex-col gap-4 bg-purple-50 p-4 rounded-xl border border-purple-100">
               <div className="text-xs font-bold text-purple-700 uppercase tracking-wider mb-1 flex items-center gap-1"><Settings2 className="w-3 h-3"/> Latent Factors (z)</div>
               
               <div>
                 <div className="flex justify-between text-xs text-purple-900 mb-1"><span>Thickness</span> <span>{thickness}%</span></div>
                 <input type="range" min="10" max="90" value={thickness} onChange={(e) => setThickness(e.target.value)} className="w-full accent-purple-500" />
               </div>
               <div>
                 <div className="flex justify-between text-xs text-purple-900 mb-1"><span>Rotation</span> <span>{rotation}°</span></div>
                 <input type="range" min="-45" max="45" value={rotation} onChange={(e) => setRotation(e.target.value)} className="w-full accent-purple-500" />
               </div>
               <div>
                 <div className="flex justify-between text-xs text-purple-900 mb-1"><span>Slant</span> <span>{slant}°</span></div>
                 <input type="range" min="-30" max="30" value={slant} onChange={(e) => setSlant(e.target.value)} className="w-full accent-purple-500" />
               </div>
            </div>

            <ArrowRight className="text-slate-300 w-8 h-8 shrink-0" />

            {/* The Observed Data (x) */}
            <div className="flex-1 flex flex-col items-center justify-center bg-green-50 p-4 rounded-xl border border-green-100 h-full min-h-[160px]">
               <div className="text-xs font-bold text-green-700 uppercase tracking-wider mb-3 flex items-center gap-1"><ImageIcon className="w-3 h-3"/> Observed Data (x)</div>
               <motion.div 
                 className="text-6xl text-slate-800"
                 style={{ 
                   fontWeight: thickness * 10,
                   transform: `rotate(${rotation}deg) skewX(${slant}deg)` 
                 }}
               >
                 3
               </motion.div>
            </div>
          </div>
          <p className="text-xs text-slate-500 text-center mt-4 bg-slate-50 p-2 rounded">
            The image <span className="font-mono text-green-600">x</span> is just the observable outcome. The sliders <span className="font-mono text-purple-600">z</span> are the true, underlying "DNA" of the image.
          </p>
        </div>

      </div>
    </div>
  );
};

// --- SLIDE 2: Why LVMs? ---
const WhyLVMsSlide = () => {
  const [activeTab, setActiveTab] = useState(0);
  const [genStep, setGenStep] = useState(0);

  const handleGenerate = () => {
    setGenStep(1);
    setTimeout(() => setGenStep(2), 600);
    setTimeout(() => setGenStep(3), 1500);
    setTimeout(() => setGenStep(0), 3000);
  };

  const tabs = [
    {
      id: "complex",
      icon: <Layers className="w-5 h-5" />,
      title: "1. Modeling Complex Data",
      content: (
        <div className="flex flex-col h-full justify-center">
          <p className="text-sm text-slate-600 mb-6 bg-blue-50 p-3 rounded-lg border border-blue-100">
            Instead of trying to map the chaotic, impossibly complex space of all real images <span className="font-mono font-bold">p(x)</span>, we cheat. We start with a <strong>Simple Prior</strong> (easy to map) and use a <strong>Conditional Network</strong> to translate it into complexity.
          </p>
          <div className="flex items-center justify-between w-full max-w-lg mx-auto bg-white p-6 rounded-xl shadow-sm border border-slate-200">
            {/* Simple Prior */}
            <div className="flex flex-col items-center w-1/3">
              <span className="text-xs font-bold text-purple-600 mb-2 text-center">Simple Prior<br/><span className="font-mono bg-purple-100 px-1 rounded">p(z)</span></span>
              <div className="w-20 h-20 bg-purple-50 rounded-full border-2 border-purple-300 flex flex-col items-center justify-end overflow-hidden relative">
                {/* Bell Curve SVG */}
                <svg viewBox="0 0 100 100" className="w-full h-full absolute bottom-0">
                  <path d="M0,100 Q20,100 40,50 T50,20 T60,50 T80,100 L100,100" fill="none" stroke="#a855f7" strokeWidth="4" />
                </svg>
                <div className="w-3 h-3 bg-purple-600 rounded-full absolute bottom-4 left-1/2 transform -translate-x-1/2 shadow-md"></div>
              </div>
              <span className="text-[10px] text-slate-400 mt-2 text-center">Neat, organized.<br/>Easy to sample from.</span>
            </div>

            {/* Conditional Likelihood */}
            <div className="flex flex-col items-center w-1/3 px-2">
              <span className="text-xs font-bold text-blue-600 mb-2 text-center">Conditional Likelihood<br/><span className="font-mono bg-blue-100 px-1 rounded">p(x|z)</span></span>
              <div className="w-full h-12 bg-blue-500 rounded flex items-center justify-center shadow-inner relative overflow-hidden">
                <div className="absolute inset-0 bg-blue-400 opacity-50" style={{ backgroundImage: 'linear-gradient(45deg, #3b82f6 25%, transparent 25%, transparent 50%, #3b82f6 50%, #3b82f6 75%, transparent 75%, transparent)'}}></div>
                <ArrowRight className="text-white w-6 h-6 relative z-10" />
              </div>
              <span className="text-[10px] text-slate-400 mt-2 text-center">The "Translator"<br/>(Neural Network)</span>
            </div>

            {/* Complex Data */}
            <div className="flex flex-col items-center w-1/3">
              <span className="text-xs font-bold text-green-600 mb-2 text-center">Complex Data<br/><span className="font-mono bg-green-100 px-1 rounded">x</span></span>
              <div className="w-20 h-20 bg-green-50 border-2 border-green-300 flex items-center justify-center p-1 relative">
                 {/* Fake complex image pixels */}
                 <div className="grid grid-cols-4 grid-rows-4 gap-0.5 w-full h-full opacity-70">
                    {Array.from({length: 16}).map((_, i) => (
                      <div key={i} className="bg-green-600 rounded-sm" style={{ opacity: Math.random() }}></div>
                    ))}
                 </div>
              </div>
              <span className="text-[10px] text-slate-400 mt-2 text-center">Messy, high-dimensional.<br/>Hard to map directly.</span>
            </div>
          </div>
        </div>
      )
    },
    {
      id: "generation",
      icon: <Zap className="w-5 h-5" />,
      title: "2. Data Generation",
      content: (
        <div className="flex flex-col h-full justify-center items-center">
          <p className="text-sm text-slate-600 mb-8 text-center max-w-md">
            Once trained, the model is a creative engine. We pick a random building block from the prior, pass it through the network, and get <strong>synthetic data</strong> that has never existed before.
          </p>
          
          <div className="flex items-center gap-6 p-6 bg-slate-50 rounded-2xl border border-slate-200">
             <div className="flex flex-col items-center relative">
               <div className="w-16 h-16 rounded-full border-2 border-dashed border-purple-400 flex items-center justify-center bg-purple-50">
                 <AnimatePresence>
                   {genStep >= 1 && (
                     <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} exit={{ scale: 0 }} className="w-4 h-4 bg-purple-600 rounded-full shadow-lg" />
                   )}
                 </AnimatePresence>
               </div>
               <span className="text-xs font-mono text-purple-600 mt-2 font-bold">z ~ p(z)</span>
             </div>

             <ArrowRight className={`w-6 h-6 transition-colors ${genStep >= 2 ? 'text-blue-500' : 'text-slate-300'}`} />

             <div className={`px-6 py-4 rounded-xl font-bold transition-colors ${genStep >= 2 ? 'bg-blue-500 text-white shadow-lg' : 'bg-slate-200 text-slate-400'}`}>
               Generator
             </div>

             <ArrowRight className={`w-6 h-6 transition-colors ${genStep >= 3 ? 'text-green-500' : 'text-slate-300'}`} />

             <div className="flex flex-col items-center">
               <div className="w-16 h-16 rounded border border-slate-300 bg-white flex items-center justify-center overflow-hidden">
                 {genStep === 3 ? (
                   <motion.div initial={{ opacity: 0, scale: 0.5 }} animate={{ opacity: 1, scale: 1 }} className="text-4xl">🐶</motion.div>
                 ) : (
                   <span className="text-slate-300 text-2xl">?</span>
                 )}
               </div>
               <span className="text-xs font-mono text-green-600 mt-2 font-bold">x_new</span>
             </div>
          </div>

          <button 
            onClick={handleGenerate}
            disabled={genStep !== 0}
            className={`mt-8 px-6 py-2 rounded-full font-bold shadow-md transition-all ${genStep === 0 ? 'bg-slate-800 text-white hover:scale-105' : 'bg-slate-300 text-slate-500 cursor-not-allowed'}`}
          >
            {genStep === 0 ? 'Draw Sample' : 'Generating...'}
          </button>
        </div>
      )
    },
    {
      id: "representation",
      icon: <Fingerprint className="w-5 h-5" />,
      title: "3. Meaningful Representations",
      content: (
        <div className="flex flex-col h-full justify-center">
          <p className="text-sm text-slate-600 mb-6 text-center max-w-lg mx-auto">
            LVMs perform extreme compression (dimensionality reduction). They figure out that a 784-pixel image doesn't need 784 numbers to describe it; it just needs a few core <strong>latent factors</strong> (like thickness, loop size, angle).
          </p>

          <div className="flex items-center justify-center gap-4">
             <div className="flex flex-col items-center">
               <div className="grid grid-cols-5 grid-rows-5 gap-0.5 w-20 h-20 bg-slate-100 p-1 rounded border border-slate-300">
                 {Array.from({length: 25}).map((_, i) => <div key={i} className={`rounded-sm ${Math.random() > 0.5 ? 'bg-slate-800' : 'bg-white'}`}></div>)}
               </div>
               <span className="text-xs font-bold text-slate-600 mt-2">784 Dimensions</span>
               <span className="text-[10px] text-slate-400">(Pixels)</span>
             </div>

             <div className="w-24 h-12 flex items-center justify-center relative">
               {/* Funnel SVG */}
               <svg viewBox="0 0 100 50" className="w-full h-full text-slate-300 fill-current">
                 <polygon points="0,0 100,20 100,30 0,50" />
               </svg>
               <span className="absolute text-[10px] font-bold text-slate-600">Encoder</span>
             </div>

             <div className="flex flex-col items-center">
               <div className="w-24 h-24 bg-purple-50 rounded-full border-2 border-purple-300 relative flex items-center justify-center shadow-inner">
                 <div className="absolute w-2 h-2 bg-purple-600 rounded-full top-6 left-6 shadow"></div>
                 <div className="absolute w-2 h-2 bg-purple-600 rounded-full bottom-8 right-8 shadow"></div>
                 <div className="absolute w-2 h-2 bg-purple-600 rounded-full top-10 right-6 shadow"></div>
                 <span className="text-xs font-mono font-bold text-purple-700/50">Z-Space</span>
               </div>
               <span className="text-xs font-bold text-purple-700 mt-2">2 Dimensions</span>
               <span className="text-[10px] text-purple-500">(e.g., Slant, Width)</span>
             </div>
          </div>
        </div>
      )
    },
    {
      id: "uncertainty",
      icon: <HelpCircle className="w-5 h-5" />,
      title: "4. Handling Uncertainty",
      content: (
        <div className="flex flex-col h-full justify-center">
          <p className="text-sm text-slate-600 mb-8 text-center max-w-lg mx-auto">
            Because LVMs map out probabilities rather than hard rules, they are excellent at guessing missing information. If an image is corrupted, the model can infer what the missing pixels <em>probably</em> were.
          </p>

          <div className="flex items-center justify-center gap-8">
            <div className="flex flex-col items-center">
              <div className="w-20 h-20 bg-slate-800 text-white font-serif text-5xl flex items-center justify-center rounded relative overflow-hidden">
                <span className="opacity-40">8</span>
                {/* Missing chunk mask */}
                <div className="absolute bottom-0 right-0 w-12 h-12 bg-white"></div>
                <div className="absolute bottom-4 right-2 text-red-500 font-bold text-xl">?</div>
              </div>
              <span className="text-xs font-bold text-slate-600 mt-3">Missing Data</span>
            </div>

            <div className="flex flex-col items-center">
              <div className="bg-slate-100 px-4 py-2 rounded-lg border border-slate-300 text-xs font-bold text-slate-600 flex items-center gap-2">
                <Activity className="w-4 h-4" /> Probabilistic Inference
              </div>
            </div>

            <div className="flex flex-col items-center">
              <div className="w-20 h-20 bg-slate-800 text-white font-serif text-5xl flex items-center justify-center rounded relative overflow-hidden">
                <span>8</span>
                {/* Reconstructed chunk mask */}
                <div className="absolute bottom-0 right-0 w-12 h-12 bg-green-500/30 border border-green-400 border-dashed backdrop-blur-sm"></div>
              </div>
              <span className="text-xs font-bold text-green-600 mt-3">Most Likely Reconstruction</span>
            </div>
          </div>
        </div>
      )
    }
  ];

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto">
      <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center shrink-0">Why Use Latent Variable Models?</h2>
      <p className="text-slate-600 mb-8 text-center max-w-2xl mx-auto shrink-0 text-sm md:text-base">
        LVMs are powerful because they give us control, compression, and creativity.
      </p>

      <div className="flex flex-col lg:flex-row gap-6 max-w-5xl mx-auto w-full flex-grow items-stretch">
        
        {/* Left Nav: The 4 Reasons */}
        <div className="lg:w-1/3 flex flex-col gap-2">
          {tabs.map((tab, idx) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(idx)}
              className={`text-left p-4 rounded-xl flex items-center gap-3 transition-all duration-200 border-l-4 ${
                activeTab === idx 
                  ? 'bg-white shadow-md border-slate-800 text-slate-800 font-bold' 
                  : 'bg-slate-50 border-transparent text-slate-500 hover:bg-slate-100 hover:text-slate-700'
              }`}
            >
              <div className={activeTab === idx ? 'text-blue-500' : 'text-slate-400'}>
                {tab.icon}
              </div>
              <span className="text-sm">{tab.title}</span>
            </button>
          ))}
        </div>

        {/* Right Pane: Visualizer */}
        <div className="lg:w-2/3 bg-white rounded-2xl shadow-lg border border-slate-200 p-6 flex flex-col relative overflow-hidden min-h-[350px]">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
              className="w-full h-full"
            >
              <h3 className="text-xl font-bold text-slate-800 mb-4 border-b pb-2">{tabs[activeTab].title.substring(3)}</h3>
              {tabs[activeTab].content}
            </motion.div>
          </AnimatePresence>
        </div>

      </div>
    </div>
  );
};

// --- SLIDE 3: The Generative Formulation ---
const FormulationSlide = () => {
  const [activeTab, setActiveTab] = useState('prior');
  const [isSimulating, setIsSimulating] = useState(false);

  // Trigger brief simulation animation when switching to marginal tab
  useEffect(() => {
    if (activeTab === 'marginal') {
      setIsSimulating(true);
      const timer = setTimeout(() => setIsSimulating(false), 3000);
      return () => clearTimeout(timer);
    }
  }, [activeTab]);

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto">
      <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center shrink-0">The Mathematical Formulation</h2>
      <p className="text-slate-600 mb-6 text-center max-w-4xl mx-auto shrink-0 text-sm md:text-base">
        The core equation <span className="font-mono bg-slate-200 px-1 rounded text-slate-800">p(x, z) = p(x|z)p(z)</span> describes how a <strong>fully trained</strong> model generates data. Let's clear up the jargon.
      </p>

      <div className="flex flex-col lg:flex-row gap-6 w-full max-w-6xl mx-auto flex-grow items-stretch pb-12">
        
        {/* LEFT PANEL: The Jargon Buster Navigation */}
        <div className="lg:w-1/3 flex flex-col gap-3">
          <div className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-2">The Components</div>
          
          <button 
            onClick={() => setActiveTab('prior')}
            className={`text-left p-4 rounded-xl border-2 transition-all ${activeTab === 'prior' ? 'bg-purple-50 border-purple-400 shadow-md' : 'bg-white border-slate-100 hover:border-slate-300'}`}
          >
            <div className="font-mono text-purple-600 font-bold mb-1 text-lg">p(z)</div>
            <div className="font-bold text-slate-700">The Random Starting Point</div>
          </button>

          <button 
            onClick={() => setActiveTab('likelihood')}
            className={`text-left p-4 rounded-xl border-2 transition-all ${activeTab === 'likelihood' ? 'bg-blue-50 border-blue-400 shadow-md' : 'bg-white border-slate-100 hover:border-slate-300'}`}
          >
            <div className="font-mono text-blue-600 font-bold mb-1 text-lg">p(x|z ; θ)</div>
            <div className="font-bold text-slate-700">The Trained Translator</div>
          </button>

          <button 
            onClick={() => setActiveTab('marginal')}
            className={`text-left p-4 rounded-xl border-2 transition-all ${activeTab === 'marginal' ? 'bg-green-50 border-green-400 shadow-md' : 'bg-white border-slate-100 hover:border-slate-300'}`}
          >
            <div className="font-mono text-green-600 font-bold mb-1 text-lg">∫ p(x|z)p(z) dz</div>
            <div className="font-bold text-slate-700">The "How Good Are We?" Test</div>
          </button>
        </div>

        {/* RIGHT PANEL: Visual Explanations */}
        <div className="lg:w-2/3 bg-white rounded-2xl shadow-lg border border-slate-200 p-6 relative overflow-hidden">
          <AnimatePresence mode="wait">
            
            {/* PRIOR TAB */}
            {activeTab === 'prior' && (
              <motion.div key="prior" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="h-full flex flex-col">
                <h3 className="text-2xl font-bold text-purple-800 mb-4 flex items-center gap-2">
                  <Target className="w-6 h-6" /> The Prior: Pure Randomness
                </h3>
                <div className="bg-purple-50 p-4 rounded-xl border border-purple-100 mb-6 text-sm text-slate-700 space-y-3">
                  <p><strong>Your Question:</strong> <em>"We don't know about the data? What is I?"</em></p>
                  <p><strong>Answer:</strong> Exactly! At this specific step, the model ignores the data entirely. It simply picks a random point from a basic mathematical shape (the prior).</p>
                  <p>The term <span className="font-mono bg-white px-1 rounded border border-purple-200">N(0, I)</span> just means a <strong>Standard Bell Curve</strong> centered at zero. The <span className="font-mono">I</span> means "Identity Matrix"—a fancy way of saying "the hidden coordinates don't mess with each other." (e.g., pulling the "thickness" slider doesn't accidentally move the "slant" slider).</p>
                </div>
                
                <div className="flex-grow flex items-center justify-center">
                  <div className="flex flex-col items-center gap-4">
                    <div className="w-32 h-32 bg-white rounded-full border-4 border-purple-200 shadow-inner relative flex items-center justify-center overflow-hidden">
                      <div className="absolute inset-0 opacity-30 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-purple-500 to-transparent"></div>
                      {/* Animated random points */}
                      <motion.div animate={{ top: ['40%', '70%', '30%', '50%'], left: ['40%', '30%', '70%', '50%'] }} transition={{ duration: 4, repeat: Infinity }} className="absolute w-4 h-4 bg-purple-600 rounded-full shadow-md" />
                    </div>
                    <span className="font-mono text-purple-600 font-bold bg-purple-50 px-3 py-1 rounded-full border border-purple-200">z = [0.12, -0.84, 0.45, ...]</span>
                  </div>
                </div>
              </motion.div>
            )}

            {/* LIKELIHOOD TAB */}
            {activeTab === 'likelihood' && (
              <motion.div key="likelihood" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="h-full flex flex-col">
                <h3 className="text-2xl font-bold text-blue-800 mb-4 flex items-center gap-2">
                  <Layers className="w-6 h-6" /> Likelihood: The Neural Decoder
                </h3>
                <div className="bg-blue-50 p-4 rounded-xl border border-blue-100 mb-4 text-sm text-slate-700 space-y-4 h-64 overflow-y-auto shadow-inner">
                  <div>
                    <p className="font-semibold text-blue-800">Q: If we feed it random z, how does it know about the data? What is θ?</p>
                    <p className="mt-1"><strong>A:</strong> The network learned <em>during training</em>! "Parameterized by θ" means the network's weights (θ) store the structural rules (e.g., "eyes go above noses"). It's like a trained artist translating a random prompt (z) based on past experience.</p>
                  </div>
                  <div className="border-t border-blue-200 pt-3">
                    <p className="font-semibold text-blue-800">Q: Like Spline Flows output (w,h,d), what exactly does this DNN output?</p>
                    <p className="mt-1"><strong>A:</strong> It outputs <strong>parameters for a probability distribution</strong>. It does <em>not</em> just output a flat image, nor just two neurons total. It outputs a Mean (μ) and Variance (σ²) <strong>for every single pixel</strong>. For a 28x28 image (784 pixels), it outputs 1,568 numbers!</p>
                  </div>
                  <div className="border-t border-blue-200 pt-3">
                    <p className="font-semibold text-blue-800">Q: How do we compare each predicted pixel with the actual data point?</p>
                    <p className="mt-1"><strong>A:</strong> We use <strong>Negative Log-Likelihood (NLL)</strong>. We take the True Pixel (e.g., <span className="font-mono bg-white px-1">0.8</span>) and ask: <em>"How likely is 0.8 on a bell curve centered at the predicted Mean (e.g. 0.5) with the predicted Variance (e.g. 0.1)?"</em></p>
                    <ul className="list-disc pl-5 mt-1 space-y-1">
                      <li>If the Mean is far from the true pixel, Loss increases (this simplifies to <strong>Mean Squared Error</strong> if variance is fixed).</li>
                      <li>If the Mean is wrong AND the Variance is tiny (overconfident), it is heavily penalized.</li>
                    </ul>
                  </div>
                </div>

                <div className="flex-grow flex items-center justify-center w-full relative">
                  
                  {/* The Pipeline Visual */}
                  <div className="flex items-center gap-2 md:gap-4 w-full justify-between px-2">
                    
                    {/* Input Z */}
                    <div className="flex flex-col items-center shrink-0">
                      <div className="w-10 h-10 md:w-12 md:h-12 bg-purple-100 rounded-lg flex flex-col items-center justify-center border-2 border-purple-400 shadow-sm">
                        <span className="font-mono font-bold text-purple-700 text-sm md:text-base">z</span>
                      </div>
                    </div>
                    
                    <ArrowRight className="text-slate-300 w-4 h-4 md:w-5 md:h-5 shrink-0" />

                    {/* Neural Network Theta */}
                    <div className="relative group shrink-0">
                      <div className="w-20 h-16 md:w-28 md:h-20 bg-slate-800 rounded-xl shadow-lg flex flex-col items-center justify-center relative overflow-hidden border-2 border-slate-700">
                         <div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_25%,rgba(255,255,255,0.05)_50%,transparent_75%,transparent_100%)] bg-[length:10px_10px] animate-[pulse_2s_linear_infinite]"></div>
                         <span className="text-white font-bold z-10 text-[10px] md:text-xs text-center">DNN<br/>Weights (θ)</span>
                      </div>
                    </div>

                    <ArrowRight className="text-slate-300 w-4 h-4 md:w-5 md:h-5 shrink-0" />

                    {/* Output Parameters (Mean & Variance) */}
                    <div className="flex flex-col items-center shrink-0 bg-blue-50 border border-blue-200 p-2 rounded-lg shadow-sm relative">
                      <span className="absolute -top-3 left-1/2 transform -translate-x-1/2 text-[8px] font-bold text-blue-600 bg-white px-1 border border-blue-200 rounded whitespace-nowrap">DNN OUTPUTS</span>
                      
                      <div className="flex gap-2 items-center">
                        {/* Mean Matrix */}
                        <div className="flex flex-col items-center relative group">
                          <span className="text-[9px] font-bold text-slate-600 mb-1">Mean (μ)</span>
                          <div className="grid grid-cols-3 grid-rows-3 gap-[1px] bg-slate-200 border border-slate-300 p-0.5">
                            {[0.9, 0.2, 0.9, 0.1, 0.9, 0.1, 0.9, 0.2, 0.9].map((val, i) => (
                              <div key={i} className={`w-3 h-3 md:w-4 md:h-4 rounded-sm ${i === 4 ? 'bg-blue-500 ring-1 ring-blue-500' : 'bg-slate-800'}`} style={{ opacity: i === 4 ? 1 : val }}></div>
                            ))}
                          </div>
                        </div>

                        {/* Variance Matrix */}
                        <div className="flex flex-col items-center opacity-70 relative group">
                          <span className="text-[9px] font-bold text-slate-600 mb-1">Var (σ²)</span>
                          <div className="grid grid-cols-3 grid-rows-3 gap-[1px] bg-slate-200 border border-slate-300 p-0.5">
                            {Array.from({length: 9}).map((_, i) => (
                              <div key={i} className={`w-3 h-3 md:w-4 md:h-4 rounded-sm ${i === 4 ? 'bg-red-500 ring-1 ring-red-500' : 'bg-red-400'}`} style={{ opacity: i === 4 ? 1 : Math.random() * 0.5 + 0.1 }}></div>
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="flex flex-col items-center justify-center shrink-0">
                      <span className="text-[8px] md:text-[9px] font-bold text-slate-400 mb-1">Sample</span>
                      <ArrowRight className="text-slate-300 w-4 h-4 md:w-5 md:h-5" />
                    </div>

                    {/* Sampled Output Data */}
                    <div className="flex flex-col items-center shrink-0">
                      <span className="text-[9px] font-bold text-green-700 mb-1">Data (x)</span>
                      <div className="w-12 h-12 md:w-16 md:h-16 bg-white rounded-lg border-2 border-green-400 flex items-center justify-center shadow-md overflow-hidden p-0.5 relative">
                        <div className="grid grid-cols-3 grid-rows-3 gap-[1px] w-full h-full bg-slate-100">
                          {[1, 0, 1, 0, 1, 0, 1, 0, 1].map((val, i) => (
                            <div key={i} className={`rounded-sm ${i === 4 ? 'ring-2 ring-red-500 z-10' : ''} ${val === 1 ? 'bg-slate-800' : 'bg-slate-200'}`}></div>
                          ))}
                        </div>
                      </div>
                    </div>

                  </div>

                  {/* Training Overlay (The Loss connection) */}
                  <div className="absolute -bottom-2 left-1/2 transform -translate-x-1/2 w-full max-w-lg">
                     <div className="border-t-2 border-dashed border-red-400 relative pt-2 flex justify-center items-center px-4">
                        <div className="absolute top-0 left-[62%] w-0 h-0 border-l-[6px] border-l-transparent border-r-[6px] border-r-transparent border-b-[8px] border-b-red-400 transform -translate-x-1/2 -mt-2"></div>
                        <div className="flex items-center gap-3 bg-white p-2 border border-red-200 rounded-lg shadow-sm">
                           <span className="text-[10px] font-bold text-red-500">LOSS: For each pixel (e.g. Center Pixel), calculate Log-Likelihood:</span>
                           <div className="flex items-center gap-1 font-mono text-[9px] bg-slate-100 px-2 py-1 rounded">
                             <span className="text-green-600 font-bold">x_true</span> ∼ <span className="text-slate-700">N(</span><span className="text-blue-600 font-bold">μ</span>, <span className="text-red-600 font-bold">σ²</span><span className="text-slate-700">)</span>
                           </div>
                        </div>
                     </div>
                  </div>

                </div>
              </motion.div>
            )}

            {/* MARGINAL TAB */}
            {activeTab === 'marginal' && (
              <motion.div key="marginal" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="h-full flex flex-col">
                <h3 className="text-2xl font-bold text-green-800 mb-4 flex items-center gap-2">
                  <Activity className="w-6 h-6" /> Marginal: Evaluating the Model
                </h3>
                <div className="bg-green-50 p-4 rounded-xl border border-green-100 mb-2 text-sm text-slate-700 space-y-3">
                  <p><strong>Your Question:</strong> <em>"What are we integrating? We haven't seen the data?"</em></p>
                  <p><strong>Answer:</strong> Here, we <em>do</em> have a real piece of data <span className="font-mono text-green-700 font-bold">x</span> (e.g., a real photo of a dog) sitting in front of us. We are asking: <em>"How good is our model at generating THIS specific photo?"</em></p>
                  <p>To find out, the computer has to ask: "If I feed <strong>every possible random z</strong> into the network, what are the total chances it spits out this exact dog photo?" Integrating (∫) means testing all infinite <span className="font-mono text-purple-700">z</span> combinations and summing up the successes.</p>
                </div>

                <div className="flex-grow flex items-center justify-center gap-8 relative mt-4">
                  {/* The Target Data */}
                  <div className="flex flex-col items-center">
                    <span className="text-xs font-bold text-green-700 mb-2">Target Data (x)</span>
                    <div className="w-20 h-20 bg-white rounded-lg border-4 border-green-500 flex items-center justify-center shadow-lg relative overflow-hidden">
                       <span className="text-4xl">🐶</span>
                    </div>
                  </div>

                  {/* The Integration Simulation */}
                  <div className="flex flex-col items-center border border-slate-200 p-4 rounded-xl bg-slate-50 w-64 relative overflow-hidden">
                    <span className="text-xs font-bold text-slate-600 mb-2 z-10">Network trying random z's...</span>
                    
                    <div className="flex items-center gap-2 z-10 h-12">
                      {isSimulating ? (
                        <>
                          <motion.div animate={{ rotate: 360 }} transition={{ duration: 0.5, repeat: Infinity }} className="font-mono text-purple-600 text-xs">z=0.4</motion.div>
                          <ArrowRight className="w-3 h-3 text-slate-400" />
                          <motion.div animate={{ opacity: [0, 1, 0] }} transition={{ duration: 0.2, repeat: Infinity }} className="text-xl">🐱</motion.div>
                          <span className="text-red-500 font-bold text-xs">NO MATCH</span>
                        </>
                      ) : (
                        <span className="text-xs text-slate-400 italic">Integration stuck (Infinite combinations)</span>
                      )}
                    </div>
                  </div>
                </div>
              </motion.div>
            )}
            
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
};

// --- SLIDE 4: Inference ---
const InferenceSlide = () => {
  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto">
      <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center">Inference: Reversing the Process</h2>
      <p className="text-slate-600 mb-8 text-center max-w-4xl mx-auto text-sm md:text-base">
        Generation goes from <span className="font-mono text-purple-600 font-bold">z</span> to <span className="font-mono text-green-600 font-bold">x</span>. <strong>Inference</strong> is the exact opposite: Given an observed data point <span className="font-mono text-green-600 font-bold">x</span> (like a photo), what exact latent values <span className="font-mono text-purple-600 font-bold">z</span> likely generated it?
      </p>

      <div className="flex flex-col lg:flex-row items-stretch justify-center gap-6 w-full max-w-6xl mx-auto flex-grow">
        
        {/* Visualizer */}
        <div className="flex-1 flex flex-col items-center justify-center gap-4 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
           <h3 className="text-slate-500 font-bold uppercase tracking-widest text-xs mb-4">The Goal</h3>
           
           <div className="flex items-center justify-center w-full gap-4">
             <div className="flex flex-col items-center">
               <div className="w-24 h-24 bg-green-100 border-2 border-green-400 rounded-lg flex items-center justify-center mb-2 shadow-md overflow-hidden">
                  <img src="https://picsum.photos/id/1025/100/100" className="w-full h-full object-cover grayscale" />
               </div>
               <span className="text-xs font-bold text-green-700 bg-green-50 px-2 rounded font-mono">x (Observed)</span>
             </div>

             <div className="flex flex-col items-center flex-grow">
               <div className="w-full flex items-center relative h-8">
                 <div className="absolute inset-0 flex items-center">
                   <div className="w-full border-t-4 border-dashed border-red-400"></div>
                 </div>
                 <div className="absolute left-0 w-0 h-0 border-r-[12px] border-r-red-400 border-t-[8px] border-t-transparent border-b-[8px] border-b-transparent"></div>
               </div>
               <div className="text-xs font-bold text-red-600 mt-2 bg-red-50 px-3 py-1 rounded font-mono border border-red-200">True Posterior: p(z|x)</div>
             </div>

             <div className="flex flex-col items-center">
               <div className="w-24 h-24 bg-purple-50 border-2 border-purple-300 border-dashed rounded-full flex items-center justify-center mb-2 shadow-sm font-bold text-4xl text-purple-400">
                 ?
               </div>
               <span className="text-xs font-bold text-purple-700 bg-purple-50 px-2 rounded font-mono">z (Unknown)</span>
             </div>
           </div>
           
           <p className="text-sm text-slate-500 mt-6 text-center max-w-sm">
             We want to find <span className="font-mono text-red-500">p(z|x)</span>. This tells us what sliders (latent factors) to pull to perfectly recreate this specific image.
           </p>
        </div>

        {/* The Math Box */}
        <div className="flex-1 bg-slate-800 p-8 rounded-2xl shadow-xl w-full text-white flex flex-col relative overflow-hidden">
          <h3 className="text-lg font-bold text-slate-200 mb-6 flex items-center gap-2 border-b border-slate-700 pb-2">
            <Search className="w-5 h-5 text-blue-400" /> Bayes' Theorem
          </h3>
          
          <p className="text-sm text-slate-400 mb-6">To reverse the probability, statistics tells us we MUST use Bayes' theorem:</p>

          <div className="flex items-center justify-center font-mono text-lg lg:text-xl bg-slate-900 py-6 px-2 rounded-xl border border-slate-700 shadow-inner relative overflow-x-auto scrollbar-hide">
            <div className="flex items-center shrink-0">
              <span className="text-red-400 font-bold mr-3">p(z|x)</span>
              <span className="mr-3">=</span>
              
              {/* First part of formula with p(x) */}
              <div className="flex flex-col items-center mr-3">
                <div className="border-b-2 border-slate-500 pb-2 px-2 flex gap-1">
                  <span className="text-blue-400">p(x|z)</span>
                  <span className="text-purple-400">p(z)</span>
                </div>
                <div className="pt-2 px-2">
                  <span className="text-green-400 font-bold bg-slate-800 px-1 rounded relative">p(x)</span>
                </div>
              </div>

              <span className="mr-3">=</span>

              {/* Second expanded part of formula */}
              <div className="flex flex-col items-center relative ml-1">
                <div className="border-b-2 border-slate-500 pb-2 px-4 flex gap-2 items-center relative">
                  <span className="text-blue-400">p(x|z)</span>
                  <span className="text-purple-400">p(z)</span>
                  <span className="absolute -top-3 right-0 bg-green-500/20 text-green-400 text-[8px] px-1 rounded">EASY</span>
                </div>
                <div className="pt-2 px-4 relative mt-1">
                  <span className="text-slate-400 font-bold">
                    ∫ p(x|z')p(z') dz'
                  </span>
                  <div className="absolute inset-0 bg-red-500/20 border-2 border-red-500 rounded flex items-center justify-center transform scale-110">
                     <div className="bg-red-600 text-white text-[10px] font-sans font-bold px-1 rounded absolute -bottom-3">IMPOSSIBLE</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          {/* The "Blocked" Stamp overlay - Moved to corner to avoid hiding the formula */}
          <div className="absolute top-6 right-6 md:top-8 md:right-8 pointer-events-none">
            <motion.div 
              initial={{ scale: 3, opacity: 0 }} 
              animate={{ scale: 1, opacity: 0.95 }} 
              transition={{ delay: 0.5, type: 'spring' }}
              className="border-4 border-red-500 text-red-500 font-bold text-xl md:text-3xl transform rotate-12 px-3 py-1 rounded-lg shadow-[0_0_20px_rgba(239,68,68,0.3)] bg-slate-800"
            >
              INTRACTABLE
            </motion.div>
          </div>
          
          <div className="mt-auto pt-6 space-y-3 text-sm text-slate-300">
            <p><strong>The Numerator is easy:</strong> We already have our Generator <span className="font-mono text-blue-400">p(x|z)</span> and our Prior <span className="font-mono text-purple-400">p(z)</span>.</p>
            <p><strong>The Denominator is broken:</strong> It requires integrating over <em>every possible</em> <span className="font-mono text-purple-400">z</span>. Because the denominator is impossible to calculate, the entire formula <span className="font-mono text-red-400">p(z|x)</span> is trapped behind a mathematical wall.</p>
          </div>
        </div>

      </div>
    </div>
  );
};

// --- SLIDE 5: Variational Inference (The Solution) ---
const VariationalInferenceSlide = () => {
  const [computing, setComputing] = useState(false);
  const [progress, setProgress] = useState(0);

  const startCompute = () => {
    setComputing(true);
    setProgress(0);
    const interval = setInterval(() => {
      setProgress(p => {
        if (p >= 99) {
          clearInterval(interval);
          return 99; // Never quite reaches 100
        }
        return p + (Math.random() * 2);
      });
    }, 100);
  };

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto">
      <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center">The Solution: Variational Inference</h2>
      <p className="text-slate-600 mb-6 text-center max-w-4xl mx-auto text-sm md:text-base">
        Since we cannot calculate the true posterior <span className="font-mono text-red-500 font-bold">p(z|x)</span>, we use a clever workaround called <strong>Variational Inference</strong>. We build a second Neural Network to <em>guess</em> the answer!
      </p>

      <div className="flex flex-col lg:flex-row items-stretch justify-center gap-6 w-full max-w-6xl mx-auto flex-grow">
        
        {/* LEFT: The Impossible Math (The Problem) */}
        <div className="flex-1 bg-red-50 p-6 rounded-2xl shadow-sm border border-red-200 flex flex-col relative overflow-hidden opacity-80">
           <h3 className="font-bold text-red-800 mb-2 flex items-center gap-2 border-b border-red-200 pb-2">
             <EyeOff className="w-5 h-5" /> The Impossible True Math
           </h3>
           <p className="text-sm text-red-700 mb-4">
             Trying to find the exact True Posterior <span className="font-mono font-bold bg-white px-1 rounded">p(z|x)</span> requires brute-forcing the integral.
           </p>

           <div className="flex-grow border border-red-300 rounded-lg bg-white p-2 relative overflow-hidden flex items-center justify-center mb-4">
              <div className="grid grid-cols-12 gap-1 w-full h-full opacity-40">
                 {Array.from({length: 144}).map((_, i) => (
                   <div key={i} className={`rounded-sm ${computing && i < (progress/100 * 144) ? 'bg-red-500' : 'bg-red-100'}`}></div>
                 ))}
              </div>
              <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none bg-white/50 backdrop-blur-[1px]">
                 <div className="text-red-700 font-mono text-3xl font-bold">{progress > 0 ? `${progress.toFixed(1)}%` : '∞'}</div>
                 {progress > 90 && <div className="text-white text-xs font-mono mt-2 bg-red-600 px-2 py-1 rounded shadow">Stuck testing all z's...</div>}
              </div>
           </div>

           <button 
             onClick={startCompute}
             disabled={computing}
             className={`w-full py-2.5 text-sm rounded font-bold transition-colors ${computing ? 'bg-red-200 text-red-500' : 'bg-red-600 text-white hover:bg-red-700'}`}
           >
             {computing ? 'Calculating Integral...' : 'Attempt Exact Inference'}
           </button>
        </div>

        {/* RIGHT: Variational Inference (The Hack) */}
        <div className="flex-[1.2] bg-teal-50 p-6 rounded-2xl shadow-lg border-2 border-teal-400 flex flex-col relative">
           <div className="absolute -top-3 right-6 bg-teal-500 text-white font-bold px-3 py-1 rounded-full text-xs shadow-md">
             The Deep Learning Hack
           </div>
           
           <h3 className="font-bold text-teal-800 mb-2 flex items-center gap-2 border-b border-teal-200 pb-2">
             <Scissors className="w-5 h-5" /> Approximate Inference
           </h3>
           <p className="text-sm text-teal-800 mb-6">
             We define a brand new Neural Network called the <strong>Encoder</strong>. We call its output <span className="font-mono font-bold bg-white px-1 rounded text-teal-600">q(z|x; φ)</span>. It skips the integral entirely.
           </p>

           <div className="flex-grow flex items-center justify-between bg-white rounded-xl border border-teal-200 p-4 shadow-sm relative">
             
             {/* The Data X */}
             <div className="flex flex-col items-center z-10">
               <div className="w-16 h-16 bg-slate-100 border-2 border-slate-300 rounded-lg flex items-center justify-center shadow-md overflow-hidden p-0.5">
                  <img src="https://picsum.photos/id/1025/100/100" className="w-full h-full object-cover grayscale" />
               </div>
               <span className="text-xs font-bold text-green-700 mt-2 font-mono">x</span>
             </div>

             <ArrowRight className="w-5 h-5 text-teal-300 z-10" />

             {/* The Encoder Network Q */}
             <div className="relative group z-10">
                <div className="w-24 h-24 bg-teal-600 rounded-xl shadow-lg flex flex-col items-center justify-center relative overflow-hidden border-2 border-teal-500">
                   <div className="absolute inset-0 bg-[linear-gradient(-45deg,transparent_25%,rgba(255,255,255,0.1)_50%,transparent_75%,transparent_100%)] bg-[length:15px_15px]"></div>
                   <span className="text-white font-bold text-sm text-center">Encoder<br/>Network (φ)</span>
                </div>
             </div>

             <ArrowRight className="w-5 h-5 text-teal-300 z-10" />

             {/* The Approximation Output */}
             <div className="flex flex-col items-center z-10 bg-teal-50 p-2 rounded-lg border border-teal-100">
                <span className="text-[10px] font-bold text-teal-800 mb-1">Guesses a Distribution</span>
                <div className="flex gap-2">
                  <div className="flex flex-col items-center">
                    <span className="text-[9px] text-slate-500 font-mono">μ_z</span>
                    <div className="w-8 h-8 bg-blue-400 rounded-sm mt-1"></div>
                  </div>
                  <div className="flex flex-col items-center">
                    <span className="text-[9px] text-slate-500 font-mono">σ²_z</span>
                    <div className="w-8 h-8 bg-red-400 rounded-sm mt-1"></div>
                  </div>
                </div>
                <span className="text-xs font-bold text-teal-700 mt-2 font-mono bg-white px-2 py-0.5 rounded shadow-sm border border-teal-200">q(z|x) ≈ p(z|x)</span>
             </div>
             
             {/* Background connecting line */}
             <div className="absolute top-1/2 left-8 right-8 h-1 bg-teal-100 transform -translate-y-1/2 z-0"></div>
           </div>

           <div className="mt-4 bg-white/60 p-3 rounded-lg text-sm text-teal-900 border border-teal-200">
             <strong>The Trick:</strong> We train the Encoder <span className="font-mono font-semibold">q</span> to spit out a Gaussian (Mean & Var) that matches the true <span className="font-mono font-semibold">p</span> as closely as possible. 
             This combination of an <strong>Encoder <span className="font-mono text-teal-600">q(z|x)</span></strong> and a <strong>Decoder <span className="font-mono text-blue-600">p(x|z)</span></strong> trained together is exactly what a <strong>Variational Autoencoder (VAE)</strong> is!
           </div>
        </div>

      </div>
    </div>
  );
};


// --- SLIDE 6: The Full VAE Picture ---
const TheFullVAESlide = () => {
  const [mode, setMode] = useState('training'); // 'training' or 'generation'

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-slate-50">
      <div className="flex flex-col items-center shrink-0 mb-6">
        <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center">The Big Picture: Variational Autoencoders</h2>
        <p className="text-slate-600 text-center max-w-3xl text-sm md:text-base">
          How do the Encoder, Decoder, and Prior all fit together? The VAE operates in two distinct modes.
        </p>
        
        {/* Toggle Switch */}
        <div className="mt-6 flex bg-slate-200 p-1 rounded-full shadow-inner border border-slate-300">
           <button 
             onClick={() => setMode('training')}
             className={`px-6 py-2 rounded-full font-bold text-sm flex items-center gap-2 transition-all ${mode === 'training' ? 'bg-white text-blue-700 shadow-md' : 'text-slate-500 hover:text-slate-700'}`}
           >
             <RefreshCw className="w-4 h-4" /> Training Phase
           </button>
           <button 
             onClick={() => setMode('generation')}
             className={`px-6 py-2 rounded-full font-bold text-sm flex items-center gap-2 transition-all ${mode === 'generation' ? 'bg-white text-purple-700 shadow-md' : 'text-slate-500 hover:text-slate-700'}`}
           >
             <Wand2 className="w-4 h-4" /> Generation Phase
           </button>
        </div>
      </div>

      <div className="flex-grow flex flex-col justify-center w-full max-w-6xl mx-auto relative">
        <AnimatePresence mode="wait">
          
          {/* TRAINING MODE */}
          {mode === 'training' && (
            <motion.div key="train" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="flex flex-col w-full h-full gap-8">
               
               {/* Main Pipeline */}
               <div className="flex items-center justify-between bg-white p-6 rounded-2xl shadow-lg border border-slate-200 relative">
                  
                  {/* Data Input */}
                  <div className="flex flex-col items-center z-10 w-24 shrink-0">
                    <span className="text-xs font-bold text-green-700 mb-2 font-mono bg-green-50 px-2 py-0.5 rounded">x_true</span>
                    <div className="w-16 h-16 bg-slate-100 border-2 border-slate-300 rounded-lg overflow-hidden p-0.5">
                       <img src="https://picsum.photos/id/1025/100/100" className="w-full h-full object-cover grayscale" />
                    </div>
                  </div>

                  <ArrowRight className="w-6 h-6 text-slate-300 shrink-0" />

                  {/* Encoder */}
                  <div className="flex flex-col items-center z-10">
                    <span className="text-[10px] font-bold text-teal-700 mb-1 uppercase tracking-wider">Encoder</span>
                    <div className="w-24 h-20 bg-teal-600 rounded-xl shadow-md flex items-center justify-center border-2 border-teal-500 text-white font-bold font-mono text-sm">
                      q(z|x; φ)
                    </div>
                  </div>

                  <ArrowRight className="w-6 h-6 text-slate-300 shrink-0" />

                  {/* Latent Space (The Bottleneck) */}
                  <div className="flex flex-col items-center z-10 bg-purple-50 p-3 rounded-xl border-2 border-purple-200 relative">
                     <span className="text-[10px] font-bold text-purple-800 mb-1 uppercase tracking-wider">Latent Space (Z)</span>
                     <div className="flex gap-2">
                       <div className="w-8 h-8 bg-blue-400 rounded-sm flex items-center justify-center text-white text-[10px] font-mono">μ</div>
                       <div className="w-8 h-8 bg-red-400 rounded-sm flex items-center justify-center text-white text-[10px] font-mono">σ²</div>
                     </div>
                     <span className="text-xs font-bold text-slate-600 mt-2 font-mono">Sample z</span>
                     
                     {/* KL Divergence Link */}
                     <div className="absolute -top-16 left-1/2 transform -translate-x-1/2 flex flex-col items-center w-48">
                        <div className="bg-white border border-purple-200 shadow-sm p-1.5 rounded-lg flex flex-col items-center w-full relative z-20">
                          <span className="text-[9px] font-bold text-purple-600">Prior Target p(z)</span>
                          <span className="text-[10px] font-mono text-slate-500">N(0, I)</span>
                        </div>
                        <div className="h-6 border-l-2 border-dashed border-red-400 w-px"></div>
                        <span className="bg-red-100 text-red-600 text-[8px] font-bold px-1 rounded absolute top-8 left-1/2 transform -translate-x-1/2 whitespace-nowrap z-30">KL Divergence Loss</span>
                     </div>
                  </div>

                  <ArrowRight className="w-6 h-6 text-slate-300 shrink-0" />

                  {/* Decoder */}
                  <div className="flex flex-col items-center z-10">
                    <span className="text-[10px] font-bold text-blue-700 mb-1 uppercase tracking-wider">Decoder</span>
                    <div className="w-24 h-20 bg-slate-800 rounded-xl shadow-md flex items-center justify-center border-2 border-slate-700 text-white font-bold font-mono text-sm">
                      p(x|z; θ)
                    </div>
                  </div>

                  <ArrowRight className="w-6 h-6 text-slate-300 shrink-0" />

                  {/* Data Output */}
                  <div className="flex flex-col items-center z-10 w-24 shrink-0">
                    <span className="text-xs font-bold text-green-700 mb-2 font-mono bg-green-50 px-2 py-0.5 rounded">x_pred</span>
                    <div className="w-16 h-16 bg-white border-2 border-green-400 rounded-lg overflow-hidden p-0.5 shadow-md">
                       <img src="https://picsum.photos/id/1025/100/100" className="w-full h-full object-cover grayscale opacity-90 blur-[0.5px]" />
                    </div>
                  </div>

                  {/* Reconstruction Loss Connector */}
                  <div className="absolute -bottom-10 left-12 right-12 h-16 border-b-2 border-l-2 border-r-2 border-dashed border-red-400 rounded-b-xl flex items-end justify-center pb-1 z-0">
                     <span className="bg-red-100 text-red-600 text-[10px] font-bold px-2 py-0.5 rounded translate-y-1/2 shadow-sm">Reconstruction Loss (NLL / MSE)</span>
                  </div>
               </div>

               {/* Explanation Box */}
               <div className="bg-blue-50 border-l-4 border-blue-500 p-5 rounded-r-xl shadow-sm mt-4">
                  <h3 className="font-bold text-blue-900 mb-2 flex items-center gap-2"><GitMerge className="w-5 h-5"/> How Training Solves Intractability</h3>
                  <p className="text-sm text-slate-700 leading-relaxed">
                    During training, we use an <strong>Encoder</strong> to guess the hidden factors <span className="font-mono bg-white px-1 rounded">z</span> for our data. But how do we ensure it learns a good latent space? We force it using the <strong>KL Divergence Loss</strong>! This loss acts like a gravitational pull, forcing the Encoder's outputs (<span className="font-mono bg-white px-1 rounded">μ, σ²</span>) to look as close to the <strong>Prior p(z)</strong> as possible. Because we successfully squish our latent space to match the Prior during training, we can rely on that Prior later.
                  </p>
               </div>
            </motion.div>
          )}

          {/* GENERATION MODE */}
          {mode === 'generation' && (
            <motion.div key="generate" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="flex flex-col w-full h-full gap-8 justify-center items-center">
               
               <div className="flex items-center justify-center bg-white p-12 rounded-2xl shadow-lg border border-slate-200 relative w-full max-w-4xl">
                  
                  {/* The Prior (Now the source) */}
                  <div className="flex flex-col items-center z-10 bg-purple-50 p-4 rounded-xl border-2 border-purple-400 shadow-md">
                     <span className="text-xs font-bold text-purple-800 mb-2 uppercase tracking-wider">The Prior</span>
                     <div className="w-20 h-20 bg-white rounded-full border-2 border-purple-200 shadow-inner relative flex items-center justify-center overflow-hidden mb-2">
                      <div className="absolute inset-0 opacity-30 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-purple-500 to-transparent"></div>
                      <div className="absolute w-3 h-3 bg-purple-600 rounded-full shadow-md" style={{ top: '60%', left: '30%' }} />
                    </div>
                     <span className="text-sm font-bold text-slate-700 font-mono">Sample z ~ N(0,I)</span>
                  </div>

                  <ArrowRight className="w-10 h-10 text-slate-300 mx-8" />

                  {/* Decoder */}
                  <div className="flex flex-col items-center z-10">
                    <span className="text-[10px] font-bold text-blue-700 mb-2 uppercase tracking-wider">Trained Decoder</span>
                    <div className="w-32 h-28 bg-slate-800 rounded-xl shadow-lg flex items-center justify-center border-2 border-slate-700 text-white font-bold font-mono text-lg">
                      p(x|z; θ)
                    </div>
                  </div>

                  <ArrowRight className="w-10 h-10 text-slate-300 mx-8" />

                  {/* Brand New Output */}
                  <div className="flex flex-col items-center z-10">
                    <span className="text-xs font-bold text-green-700 mb-2 font-mono bg-green-50 px-2 py-0.5 rounded">x_new</span>
                    <div className="w-24 h-24 bg-white border-4 border-green-400 rounded-lg overflow-hidden p-1 shadow-xl">
                       <img src="https://picsum.photos/id/237/100/100" className="w-full h-full object-cover grayscale" />
                    </div>
                  </div>

                  {/* Overlay indicating the missing encoder */}
                  <div className="absolute top-4 left-4 text-slate-400 text-sm font-bold flex items-center gap-2 opacity-50">
                    <Scissors className="w-4 h-4"/> Encoder discarded!
                  </div>
               </div>

               {/* Explanation Box */}
               <div className="bg-purple-50 border-l-4 border-purple-500 p-5 rounded-r-xl shadow-sm mt-4 w-full max-w-4xl">
                  <h3 className="font-bold text-purple-900 mb-2 flex items-center gap-2"><Wand2 className="w-5 h-5"/> Generation is Magic (Because of Training)</h3>
                  <p className="text-sm text-slate-700 leading-relaxed">
                    Once the VAE is fully trained, <strong>we completely throw away the Encoder and the training data</strong>. Why does this work? Because during training, the KL Divergence forced the Encoder to pack all the meaningful "DNA" of our images neatly into the shape of our simple Gaussian Prior <span className="font-mono bg-white px-1 rounded">p(z)</span>. Now, we can just grab <em>any</em> random coordinate from that Gaussian prior, feed it to our Decoder, and guarantee that it will generate a brand new, realistic piece of data!
                  </p>
               </div>
            </motion.div>
          )}

        </AnimatePresence>
      </div>
    </div>
  );
};


// --- MAIN SLIDESHOW COMPONENT ---
const Slideshow = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const slides = [
    CoreConceptSlide,
    WhyLVMsSlide,
    FormulationSlide,
    InferenceSlide,
    VariationalInferenceSlide,
    TheFullVAESlide, // The new combined VAE slide!
  ];

  const nextSlide = () => setCurrentSlide((prev) => (prev + 1) % slides.length);
  const prevSlide = () => setCurrentSlide((prev) => (prev - 1 + slides.length) % slides.length);

  const CurrentSlideComponent = slides[currentSlide];

  return (
    <div className="flex flex-col min-h-full bg-slate-100 font-sans">
      {/* Top Progress Bar */}
      <div className="w-full h-1.5 bg-slate-200 shrink-0">
        <motion.div
          className="h-full bg-slate-800"
          initial={{ width: '0%' }}
          animate={{ width: `${((currentSlide + 1) / slides.length) * 100}%` }}
        />
      </div>

      {/* Main Content Area */}
      <div className="flex-grow overflow-y-auto">
        <AnimatePresence mode='wait'>
          <motion.div
            key={currentSlide}
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -50 }}
            transition={{ duration: 0.3, ease: "easeOut" }}
          >
            <CurrentSlideComponent />
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Bottom Navigation */}
      <div className="flex justify-between items-center p-4 md:p-6 bg-white shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.05)] z-10 shrink-0">
        <button
          onClick={prevSlide}
          className="p-3 rounded-full bg-slate-100 text-slate-600 hover:bg-slate-200 transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
          disabled={currentSlide === 0}
        >
          <ChevronLeft className="w-6 h-6" />
        </button>
        
        <div className="flex space-x-2 md:space-x-3">
          {slides.map((_, i) => (
            <div
              key={i}
              className={`w-2.5 h-2.5 md:w-3 md:h-3 rounded-full transition-all duration-300 ${i === currentSlide ? 'bg-slate-800 scale-125' : 'bg-slate-300'}`}
            />
          ))}
        </div>
        
        <button
          onClick={nextSlide}
          className="p-3 rounded-full bg-slate-800 text-white hover:bg-slate-700 shadow-md transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
          disabled={currentSlide === slides.length - 1}
        >
          <ChevronRight className="w-6 h-6" />
        </button>
      </div>
    </div>
  );
};

export default function App() {
  return (
    <div className="App">
      <Slideshow />
    </div>
  );
}