import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ChevronLeft, ChevronRight, Calculator, 
  ArrowRight, Search, EyeOff, BrainCircuit, 
  ArrowDown, RotateCcw, Target, Layers, 
  CheckCircle, Zap, ShieldAlert, Split,
  Network, Database, Sparkles, BookOpen
} from 'lucide-react';

// --- SLIDE 1: The Goal & The Problem ---
const TheGoalSlide = () => {
  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-slate-50">
      <div className="flex flex-col items-center shrink-0 mb-8">
        <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center">The Goal: Marginal Log-Likelihood</h2>
        <p className="text-slate-600 text-center max-w-4xl text-sm md:text-base">
          Before doing any algebra, we must understand our ultimate objective. We want our generative model to perfectly capture the reality of our training data.
        </p>
      </div>

      <div className="flex flex-col lg:flex-row gap-8 max-w-6xl mx-auto w-full flex-grow items-center pb-8">
        
        {/* Left: The Formula Breakdown */}
        <div className="flex-1 bg-slate-900 rounded-2xl shadow-xl p-8 border border-slate-700 text-white w-full">
           <h3 className="font-bold text-blue-400 mb-6 text-sm uppercase tracking-widest flex items-center gap-2">
             <Target className="w-5 h-5"/> Our Objective Function
           </h3>
           <div className="flex justify-center mb-8">
              <span className="font-mono text-3xl font-bold bg-slate-800 px-6 py-4 rounded-xl shadow-inner border border-slate-600">
                Maximize: <span className="text-blue-400">log p<sub className="text-sm">θ</sub>(x)</span>
              </span>
           </div>
           
           <ul className="space-y-6">
             <li className="flex gap-4 items-start">
               <div className="w-10 h-10 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center shrink-0 font-bold font-mono text-lg">p</div>
               <div>
                 <strong className="text-blue-300 text-lg">Probability (Likelihood)</strong>
                 <p className="text-sm text-slate-400 mt-1">We want the model to assign a very high probability to the real images in our dataset. If it gives a real cat photo a 99% probability, the model is good!</p>
               </div>
             </li>
             <li className="flex gap-4 items-start">
               <div className="w-10 h-10 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center shrink-0 font-bold font-mono text-lg">θ</div>
               <div>
                 <strong className="text-emerald-300 text-lg">Model Parameters (Theta)</strong>
                 <p className="text-sm text-slate-400 mt-1">These are the weights and biases of our neural network (specifically, the Decoder). We want to find the optimal θ that maximizes the probability.</p>
               </div>
             </li>
             <li className="flex gap-4 items-start">
               <div className="w-10 h-10 rounded-full bg-rose-500/20 text-rose-400 flex items-center justify-center shrink-0 font-bold font-mono text-lg">log</div>
               <div>
                 <strong className="text-rose-300 text-lg">The Logarithm</strong>
                 <p className="text-sm text-slate-400 mt-1">Probabilities are tiny decimals (e.g., 0.0001). Multiplying thousands of tiny decimals causes computers to round down to 0 (underflow). Taking the <strong>log</strong> turns multiplication into addition, making the math stable. Maximizing p(x) is mathematically identical to maximizing log p(x).</p>
               </div>
             </li>
           </ul>
        </div>

        {/* Right: The Intractability */}
        <div className="flex-1 bg-white rounded-2xl shadow-lg border border-slate-200 p-8 flex flex-col w-full">
           <h3 className="font-bold text-rose-600 mb-4 text-sm uppercase tracking-widest flex items-center gap-2">
             <ShieldAlert className="w-5 h-5"/> The Intractability Problem
           </h3>
           <p className="text-sm text-slate-600 mb-6 leading-relaxed">
             If our model uses latent variables <span className="font-mono font-bold text-purple-600">z</span> to generate data, the only way to calculate the total probability of an image <span className="font-mono font-bold text-blue-600">x</span> is to calculate how likely it is to be generated by <strong>every possible latent variable</strong>.
           </p>

           <div className="bg-rose-50 border border-rose-200 p-6 rounded-xl flex justify-center mb-6 shadow-inner">
             <span className="font-mono text-xl text-rose-900 font-bold">
               p<sub className="text-xs">θ</sub>(x) = <span className="text-rose-600 text-3xl">∫</span> p<sub className="text-xs">θ</sub>(x|z) p(z) <span className="text-rose-600">dz</span>
             </span>
           </div>

           <div className="space-y-4 text-sm text-slate-700">
             <p>The <span className="font-mono font-bold text-rose-600">∫ dz</span> (integral) means "sum over all infinite possible combinations of z."</p>
             <p>Because the neural network <span className="font-mono font-bold">p<sub className="text-[10px]">θ</sub>(x|z)</span> is highly complex, and <span className="font-mono font-bold text-purple-600">z</span> is high-dimensional (e.g., 100 dimensions), this integral is impossible to solve.</p>
             <div className="bg-slate-800 text-white p-3 rounded-lg text-center font-bold uppercase tracking-widest animate-pulse mt-4">
               Directly Maximizing log p(x) is Impossible
             </div>
           </div>
        </div>

      </div>
    </div>
  );
};

// --- SLIDE 2: The Variational Hack ---
const VariationalHackSlide = () => {
  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-slate-50">
      <div className="flex flex-col items-center shrink-0 mb-6">
        <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center">Enter Variational Inference</h2>
        <p className="text-slate-600 text-center max-w-4xl text-sm md:text-base">
          To encode data, we need the True Posterior <span className="font-mono font-bold text-rose-600">p<sub className="text-xs">θ</sub>(z|x)</span>. But Bayes' rule says <span className="font-mono">p(z|x) = p(x|z)p(z) / p(x)</span>. Because <span className="font-mono">p(x)</span> is impossible to compute, the True Posterior is also trapped behind an impossible integral!
        </p>
      </div>

      <div className="flex-grow flex items-center justify-center w-full max-w-5xl mx-auto pb-8">
        <div className="bg-white p-8 rounded-3xl shadow-xl border border-slate-200 w-full flex flex-col md:flex-row gap-8 items-center">
           
           {/* The True Posterior (Impossible) */}
           <div className="flex-1 flex flex-col items-center">
             <h3 className="font-bold text-rose-800 mb-4 uppercase tracking-widest text-xs">The Impossible Truth</h3>
             <div className="w-40 h-40 bg-rose-50 border-4 border-dashed border-rose-300 rounded-full flex flex-col items-center justify-center relative shadow-sm">
                <span className="font-mono text-2xl font-bold text-rose-600">p<sub className="text-sm">θ</sub>(z|x)</span>
                <span className="text-[10px] text-rose-500 mt-2 font-bold text-center leading-tight">True Posterior<br/>(Unknown)</span>
                <div className="absolute inset-0 bg-white/50 backdrop-blur-[1px] rounded-full flex items-center justify-center">
                  <div className="bg-rose-600 text-white text-[10px] font-bold px-2 py-1 rounded shadow-lg transform rotate-[-15deg]">INTRACTABLE</div>
                </div>
             </div>
           </div>

           {/* The Bridge (VI) */}
           <div className="flex flex-col items-center gap-2">
             <span className="text-xs font-bold text-slate-400 uppercase tracking-widest text-center">Variational Inference</span>
             <ArrowRight className="w-8 h-8 text-indigo-400" />
             <span className="text-[10px] text-slate-500 font-mono">Approximate with Neural Net!</span>
           </div>

           {/* The Variational Posterior (Tractable) */}
           <div className="flex-1 flex flex-col items-center">
             <h3 className="font-bold text-emerald-800 mb-4 uppercase tracking-widest text-xs">The Deep Learning Hack</h3>
             <div className="w-40 h-40 bg-emerald-50 border-4 border-emerald-400 rounded-full flex flex-col items-center justify-center relative shadow-lg">
                <span className="font-mono text-2xl font-bold text-emerald-600">q<sub className="text-sm">φ</sub>(z|x)</span>
                <span className="text-[10px] text-emerald-700 mt-2 font-bold text-center leading-tight">Approximate Posterior<br/>(The Encoder)</span>
                <div className="absolute -bottom-4 bg-slate-800 text-emerald-400 px-3 py-1 rounded-full text-[10px] font-bold shadow-md">
                  Parameters φ
                </div>
             </div>
           </div>

        </div>
      </div>

      <div className="bg-indigo-50 border-l-4 border-indigo-500 p-6 rounded-r-xl max-w-4xl mx-auto w-full shadow-sm mb-8">
        <h4 className="font-bold text-indigo-900 mb-2">The Variational Strategy</h4>
        <p className="text-sm text-slate-700 leading-relaxed">
          Instead of solving the impossible integral, we invent a brand new neural network: the <strong>Encoder <span className="font-mono font-bold text-emerald-600">q<sub className="text-[10px]">φ</sub>(z|x)</span></strong>. 
          Its job is to guess the hidden variables <span className="font-mono">z</span>. Now, our mathematical goal changes: <strong>How can we rewrite the impossible <span className="font-mono">log p(x)</span> formula to use our new tractable Encoder instead?</strong>
        </p>
      </div>
    </div>
  );
};

// --- SLIDE 3: The Math Derivation (Step-by-Step) ---
const MathDerivationSlide = () => {
  const [step, setStep] = useState(0);

  const derivationSteps = [
    {
      title: "1. The Expectation Trick",
      equation: (
        <span>
          log <span className="text-blue-400">p<sub className="text-xs">θ</sub>(x)</span> = <span className="text-emerald-500">E<sub className="text-[10px]">q<sub className="text-[8px]">φ</sub>(z|x)</sub></span>[ log <span className="text-blue-400">p<sub className="text-xs">θ</sub>(x)</span> ]
        </span>
      ),
      text: "We wrap our target in an Expected Value (E) taken over our Encoder q. Why? Because log p(x) doesn't contain z! The 'average' of a constant is just itself. This mathematically brings our Encoder 'q' into the equation legally."
    },
    {
      title: "2. Bayes' Rule",
      equation: (
        <span>
          = <span className="text-emerald-500">E<sub className="text-[10px]">q</sub></span>[ log ( <span className="text-purple-400">p<sub className="text-xs">θ</sub>(x,z)</span> / <span className="text-rose-500">p<sub className="text-xs">θ</sub>(z|x)</span> ) ]
        </span>
      ),
      text: "We use the conditional probability rule: p(x) = p(x,z) / p(z|x). Notice that the impossible True Posterior (in red) has appeared in the denominator!"
    },
    {
      title: "3. The 'Multiply by 1' Hack",
      equation: (
        <span>
          = <span className="text-emerald-500">E<sub className="text-[10px]">q</sub></span>[ log ( (<span className="text-purple-400">p<sub className="text-xs">θ</sub>(x,z)</span> / <span className="text-rose-500">p<sub className="text-xs">θ</sub>(z|x)</span>) × <span className="text-emerald-500 bg-emerald-100 px-1 rounded">(q<sub className="text-[10px]">φ</sub>(z|x) / q<sub className="text-[10px]">φ</sub>(z|x))</span> ) ]
        </span>
      ),
      text: "Here is the genius trick. We multiply the inside of the log by (q/q). Since a number divided by itself is 1, this doesn't change the value, but it lets us rearrange the terms."
    },
    {
      title: "4. Rearranging with Log Rules",
      equation: (
        <span>
          = <span className="text-emerald-500">E<sub className="text-[10px]">q</sub></span>[ log ( <span className="text-purple-400">p<sub className="text-xs">θ</sub>(x,z)</span> / <span className="text-emerald-500 font-bold">q<sub className="text-[10px]">φ</sub>(z|x)</span> ) ] <span className="text-slate-400 font-bold">+</span> <span className="text-emerald-500">E<sub className="text-[10px]">q</sub></span>[ log ( <span className="text-emerald-500 font-bold">q<sub className="text-[10px]">φ</sub>(z|x)</span> / <span className="text-rose-500">p<sub className="text-xs">θ</sub>(z|x)</span> ) ]
        </span>
      ),
      text: "Using the property log(ab) = log(a) + log(b), we group the joint probability with our Encoder (Term 1), and group our Encoder with the impossible True Posterior (Term 2)."
    },
    {
      title: "5. Discovering ELBO and KL Divergence",
      equation: (
        <span>
          log <span className="text-blue-400">p<sub className="text-xs">θ</sub>(x)</span> = <span className="text-emerald-500 font-bold text-2xl">L(θ, φ; x)</span> + <span className="text-rose-500 font-bold text-2xl">D<sub className="text-sm">KL</sub>(q<sub className="text-xs">φ</sub> || p<sub className="text-xs">θ</sub>)</span>
        </span>
      ),
      text: "Term 1 is defined as the Evidence Lower Bound (ELBO). Term 2 is the exact formula for KL Divergence! We have successfully split the impossible Log-Likelihood into two distinct parts."
    }
  ];

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-slate-900 text-slate-200">
      <div className="flex flex-col items-center shrink-0 mb-6">
        <h2 className="text-3xl font-bold text-white mb-2 text-center">The Variational Derivation</h2>
        <p className="text-slate-400 text-center max-w-4xl text-sm md:text-base">
          Let's slowly step through the algebra that cracks the intractability problem.
        </p>
      </div>

      <div className="flex-grow flex flex-col items-center justify-center max-w-5xl mx-auto w-full">
         <div className="bg-slate-800 border-2 border-slate-700 rounded-2xl w-full p-6 md:p-10 shadow-2xl relative overflow-hidden min-h-[400px] flex flex-col">
            
            <div className="flex-grow flex flex-col justify-center">
              <AnimatePresence mode="wait">
                <motion.div 
                  key={step}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  transition={{ duration: 0.3 }}
                  className="flex flex-col items-center text-center"
                >
                  <h3 className="text-indigo-400 font-bold text-sm uppercase tracking-widest mb-6 border-b border-slate-700 pb-2 inline-block px-4">
                    {derivationSteps[step].title}
                  </h3>
                  
                  <div className="font-mono text-xl md:text-3xl font-bold bg-slate-900 px-6 py-8 rounded-xl shadow-inner border border-slate-700 mb-8 w-full max-w-3xl leading-relaxed">
                    {derivationSteps[step].equation}
                  </div>
                  
                  <p className="text-slate-300 text-base md:text-lg max-w-2xl mx-auto leading-relaxed border-l-4 border-indigo-500 pl-4 text-left">
                    {derivationSteps[step].text}
                  </p>
                </motion.div>
              </AnimatePresence>
            </div>

            <div className="mt-8 flex justify-between items-center w-full max-w-3xl mx-auto border-t border-slate-700 pt-6">
               <button 
                 onClick={() => setStep(Math.max(0, step - 1))}
                 disabled={step === 0}
                 className="flex items-center gap-2 px-6 py-2 bg-slate-700 hover:bg-slate-600 disabled:opacity-30 disabled:cursor-not-allowed rounded-lg font-bold text-white transition-colors"
               >
                 <ChevronLeft className="w-5 h-5"/> Previous
               </button>
               
               <div className="flex gap-2">
                 {derivationSteps.map((_, i) => (
                   <div key={i} className={`w-2 h-2 rounded-full ${i === step ? 'bg-indigo-500' : 'bg-slate-600'}`}></div>
                 ))}
               </div>

               <button 
                 onClick={() => setStep(Math.min(derivationSteps.length - 1, step + 1))}
                 disabled={step === derivationSteps.length - 1}
                 className="flex items-center gap-2 px-6 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-30 disabled:cursor-not-allowed rounded-lg font-bold text-white transition-colors"
               >
                 Next <ChevronRight className="w-5 h-5"/>
               </button>
            </div>

         </div>
      </div>
    </div>
  );
};

// --- SLIDE 4: The ELBO Block Diagram (From Screenshot) ---
const ELBOBlockDiagramSlide = () => {
  const [approxQuality, setApproxQuality] = useState(20); // 0 to 100

  // Derived heights for the visualizer
  const klGapHeight = 100 - approxQuality;
  const elboHeight = approxQuality;

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-[#1e1e1e]">
      <div className="flex flex-col items-center shrink-0 mb-6">
        <h2 className="text-3xl font-bold text-white mb-2 text-center">The Fundamental Identity</h2>
        <p className="text-slate-400 text-center max-w-4xl text-sm md:text-base">
          This exact decomposition reveals why it's called the "Evidence Lower Bound". Let's recreate the core relationship visually.
        </p>
      </div>

      <div className="flex-grow flex flex-col items-center justify-center w-full max-w-4xl mx-auto pb-8">
        
        {/* The Exact Screenshot Recreation */}
        <div className="w-full flex flex-col items-center justify-center gap-2 relative mt-4">
           
           {/* Top Block: Marginal Log Likelihood */}
           <div className="bg-[#a5d6ff] rounded-xl w-[350px] py-6 flex flex-col items-center justify-center shadow-lg relative z-10">
              <span className="font-mono text-slate-800 font-bold mb-1">log p<sub className="text-xs">θ</sub>(x)</span>
              <span className="text-slate-700 text-sm">(Marginal Log-Likelihood)</span>
           </div>

           <div className="h-8 w-px bg-slate-500"></div>

           {/* Equal Sign Block */}
           <div className="bg-[#cccccc] rounded-xl w-16 h-12 flex items-center justify-center font-bold text-xl text-slate-800 shadow-sm relative z-10">
             =
           </div>

           <div className="h-8 w-px bg-slate-500"></div>

           {/* Bottom Row: ELBO + KL */}
           <div className="flex items-center gap-4 w-full max-w-3xl justify-center h-[120px]">
              
              {/* ELBO Block (Grows) */}
              <div className="w-[350px] h-full flex flex-col justify-end relative">
                {/* Dotted upward arrow from yellow box */}
                <div className="absolute -bottom-8 left-1/2 w-0 h-0 border-l-[6px] border-l-transparent border-r-[6px] border-r-transparent border-b-[8px] border-b-slate-400 transform -translate-x-1/2 z-20"></div>
                <div className="absolute -bottom-16 left-1/2 w-px h-16 border-l-2 border-dashed border-slate-400 transform -translate-x-1/2 z-10"></div>
                
                <motion.div 
                  className="bg-[#9bf6cc] rounded-xl w-full flex flex-col items-center justify-center shadow-lg overflow-hidden border border-[#7de5b4]"
                  animate={{ height: `${elboHeight}%` }}
                  transition={{ type: "spring", stiffness: 100, damping: 20 }}
                  style={{ minHeight: '40px' }}
                >
                   {elboHeight > 40 && (
                     <>
                       <span className="font-mono text-slate-800 font-bold mb-1 text-sm">L(θ, φ; x)</span>
                       <span className="text-slate-700 text-xs">Evidence Lower Bound (ELBO)</span>
                     </>
                   )}
                </motion.div>
              </div>

              {/* Plus Sign */}
              <div className="bg-[#cccccc] rounded-xl w-14 h-12 flex items-center justify-center font-bold text-xl text-slate-800 shadow-sm shrink-0">
                +
              </div>

              {/* KL Divergence Block (Shrinks) */}
              <div className="w-[350px] h-full flex flex-col justify-end">
                <motion.div 
                  className="bg-[#ffc2c2] rounded-xl w-full flex flex-col items-center justify-center shadow-lg overflow-hidden border border-[#ffafaf]"
                  animate={{ height: `${klGapHeight}%` }}
                  transition={{ type: "spring", stiffness: 100, damping: 20 }}
                  style={{ minHeight: '10px' }}
                >
                   {klGapHeight > 40 && (
                     <>
                       <span className="font-mono text-slate-800 font-bold mb-1 text-sm">D<sub className="text-[10px]">KL</sub>(q<sub className="text-[10px]">φ</sub>(z|x) || p<sub className="text-[10px]">θ</sub>(z|x))</span>
                       <span className="text-slate-700 text-xs">Approximation Gap (≥0)</span>
                     </>
                   )}
                </motion.div>
              </div>

           </div>

           {/* The Objective Note (Yellow Box) */}
           <div className="bg-[#ffe8a1] rounded-lg border border-amber-300 p-4 mt-8 w-full max-w-xl text-center text-slate-800 shadow-md relative z-30">
              <div className="absolute -top-1 -right-1 w-3 h-3 bg-[#e5c96b] transform rotate-45"></div> {/* Fake dog-ear corner */}
              <p className="font-bold text-sm mb-1">Objective: Maximize L(θ, φ; x)</p>
              <p className="text-xs">This simultaneously maximizes log p<sub className="text-[10px]">θ</sub>(x) (our goal)</p>
              <p className="text-xs">and minimizes D<sub className="text-[10px]">KL</sub>(q<sub className="text-[10px]">φ</sub>(z|x) || p<sub className="text-[10px]">θ</sub>(z|x)) (improves approximation)</p>
           </div>
        </div>

        {/* Interactive Slider */}
        <div className="w-full max-w-md mt-10 bg-slate-800 p-4 rounded-xl border border-slate-700 shadow-inner flex flex-col gap-2">
           <div className="flex justify-between text-[10px] font-bold text-slate-400 uppercase tracking-widest">
             <span className="text-amber-400">Optimize Model (Train)</span>
             <span className="text-emerald-400">Perfect Approximation</span>
           </div>
           <input type="range" min="10" max="95" value={approxQuality} onChange={(e) => setApproxQuality(e.target.value)} className="w-full accent-emerald-500" />
           <p className="text-xs text-slate-400 mt-2 text-center">
             Because KL is always ≥ 0, the ELBO acts as a floor pushing up the Marginal Likelihood. Squeeze the KL gap to 0!
           </p>
        </div>

      </div>
    </div>
  );
};

// --- SLIDE 5: Rewriting ELBO for VAEs ---
const ELBORewriteSlide = () => {
  const [step, setStep] = useState(0);

  const rewriteSteps = [
    {
      eq: <span><span className="text-emerald-400">L(θ, φ; x)</span> = E<sub className="text-xs">q</sub>[ log p(x,z) - log q(z|x) ]</span>,
      desc: "Starting point: The ELBO definition from earlier, using log division rules."
    },
    {
      eq: <span>= E<sub className="text-xs">q</sub>[ log <span className="text-purple-400">( p(x|z)p(z) )</span> - log q(z|x) ]</span>,
      desc: "We expand the joint probability p(x,z) into the likelihood p(x|z) multiplied by the prior p(z)."
    },
    {
      eq: <span>= E<sub className="text-xs">q</sub>[ log p(x|z) + log p(z) - log q(z|x) ]</span>,
      desc: "Log rules again: log(a * b) = log(a) + log(b)."
    },
    {
      eq: <span>= <span className="text-blue-400 font-bold">E<sub className="text-xs">q</sub>[ log p(x|z) ]</span> - <span className="text-rose-400 font-bold">E<sub className="text-xs">q</sub>[ log q(z|x) - log p(z) ]</span></span>,
      desc: "We group the terms. We pull out the p(x|z) term, and factor out a negative sign for the remaining q and p(z) terms."
    },
    {
      eq: <span>= <span className="text-blue-400 font-bold">E<sub className="text-[10px]">q<sub className="text-[8px]">φ</sub>(z|x)</sub>[ log p<sub className="text-[10px]">θ</sub>(x|z) ]</span> - <span className="text-rose-400 font-bold">D<sub className="text-sm">KL</sub>( q<sub className="text-[10px]">φ</sub>(z|x) || p(z) )</span></span>,
      desc: "The second term is the exact mathematical definition of KL Divergence! This is the most common and intuitive form of the ELBO used in VAEs."
    }
  ];

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-slate-50">
      <div className="flex flex-col items-center shrink-0 mb-6">
        <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center">Rewriting ELBO for VAEs</h2>
        <p className="text-slate-600 text-center max-w-4xl text-sm md:text-base">
          The ELBO formula we found <span className="font-mono text-xs bg-slate-200 px-1 rounded">E[log(p(x,z)/q(z|x))]</span> is correct, but hard to code in PyTorch. Let's rewrite it using basic algebra into the famous two-part VAE loss function.
        </p>
      </div>

      <div className="flex-grow flex flex-col items-center justify-center max-w-5xl mx-auto w-full">
         <div className="bg-white border border-slate-200 rounded-2xl w-full p-8 shadow-xl relative overflow-hidden flex flex-col">
            
            <div className="flex flex-col gap-6 w-full max-w-3xl mx-auto">
              {rewriteSteps.map((s, idx) => (
                <div key={idx} className="flex flex-col md:flex-row items-center md:items-start gap-4 w-full">
                  {/* Connection arrow logic */}
                  <div className="hidden md:flex flex-col items-center w-8 shrink-0 relative mt-2">
                     {idx > 0 && <ArrowDown className={`w-5 h-5 ${idx <= step ? 'text-indigo-500' : 'text-slate-200'}`} />}
                  </div>
                  
                  {/* Equation Block */}
                  <motion.div 
                    initial={{ opacity: 0, x: -20 }} animate={{ opacity: idx <= step ? 1 : 0.2, x: 0 }}
                    className={`flex-1 p-4 rounded-xl font-mono text-sm md:text-lg border-2 transition-colors duration-300 w-full text-center md:text-left ${idx === step ? 'bg-indigo-50 border-indigo-400 shadow-md text-indigo-900 font-bold' : idx < step ? 'bg-slate-50 border-slate-200 text-slate-600' : 'bg-transparent border-slate-100 text-slate-400'}`}
                  >
                    {s.eq}
                  </motion.div>
                </div>
              ))}
            </div>

            <div className="mt-8 bg-slate-800 p-4 rounded-xl flex items-center justify-between w-full max-w-3xl mx-auto border-2 border-slate-700">
               <button onClick={() => setStep(Math.max(0, step - 1))} disabled={step===0} className="px-4 py-2 bg-slate-700 text-white rounded font-bold text-sm disabled:opacity-50">Previous</button>
               <span className="text-slate-400 text-xs font-bold uppercase tracking-widest">{step === 4 ? "Derivation Complete!" : "Click Next to expand"}</span>
               <button onClick={() => setStep(Math.min(4, step + 1))} disabled={step===4} className="px-4 py-2 bg-indigo-600 text-white rounded font-bold text-sm disabled:opacity-50 hover:bg-indigo-500 shadow">Next Algebra Step</button>
            </div>

            <AnimatePresence>
              {step === 4 && (
                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mt-8 bg-emerald-50 border border-emerald-200 p-5 rounded-xl max-w-3xl mx-auto w-full flex gap-4 shadow-sm items-start">
                  <CheckCircle className="w-6 h-6 text-emerald-600 shrink-0 mt-0.5" />
                  <p className="text-sm text-emerald-900">
                    <strong>Why did we do this?</strong> Look at the final equation. It perfectly separates the math into an <strong>Encoder term</strong> (the KL Divergence matching <span className="font-mono">q</span> to the Prior <span className="font-mono">p</span>) and a <strong>Decoder term</strong> (the Log Likelihood measuring reconstruction). This tells us exactly how to build the neural networks!
                  </p>
                </motion.div>
              )}
            </AnimatePresence>
         </div>
      </div>
    </div>
  );
};

// --- SLIDE 6: The Final VAE Objective ---
const VAEObjectiveSlide = () => {
  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-slate-900 text-white">
      <div className="flex flex-col items-center shrink-0 mb-6">
        <h2 className="text-3xl font-bold text-white mb-2 text-center">Deconstructing the Objective</h2>
        <p className="text-slate-400 text-center max-w-4xl text-sm md:text-base">
          This final ELBO formula governs exactly how the Variational Autoencoder learns. It is a balancing act between two distinct forces.
        </p>
      </div>

      <div className="flex flex-col gap-8 max-w-6xl mx-auto w-full flex-grow items-stretch pb-8">
        
        {/* The Giant Formula Box */}
        <div className="bg-slate-800 rounded-2xl shadow-2xl border border-slate-600 p-6 flex flex-col items-center relative w-full shrink-0">
           <span className="absolute -top-3 bg-emerald-500 text-white text-[10px] font-bold px-3 py-1 rounded-full shadow-lg tracking-widest uppercase">The VAE Loss Function</span>
           <div className="font-mono text-xl md:text-3xl font-bold text-white text-center flex flex-wrap justify-center items-center gap-4 mt-2">
             <span>L(θ, φ; x) =</span>
             <div className="relative group">
               <span className="bg-blue-900/50 text-blue-400 border-2 border-blue-500/50 px-4 py-3 rounded-xl inline-block shadow-[0_0_15px_rgba(59,130,246,0.3)]">E<sub className="text-xs">q<sub className="text-[10px]">φ</sub>(z|x)</sub>[ log p<sub className="text-xs">θ</sub>(x|z) ]</span>
               <div className="absolute -bottom-8 left-1/2 transform -translate-x-1/2 w-0 h-0 border-l-[8px] border-l-transparent border-r-[8px] border-r-transparent border-t-[8px] border-t-blue-500/50"></div>
             </div>
             <span className="text-slate-500 text-4xl">-</span>
             <div className="relative group">
               <span className="bg-rose-900/50 text-rose-400 border-2 border-rose-500/50 px-4 py-3 rounded-xl inline-block shadow-[0_0_15px_rgba(244,63,94,0.3)]">D<sub className="text-xs">KL</sub>( q<sub className="text-[10px]">φ</sub>(z|x) || p(z) )</span>
               <div className="absolute -bottom-8 left-1/2 transform -translate-x-1/2 w-0 h-0 border-l-[8px] border-l-transparent border-r-[8px] border-r-transparent border-t-[8px] border-t-rose-500/50"></div>
             </div>
           </div>
        </div>

        {/* Breakdown Panels */}
        <div className="flex flex-col lg:flex-row gap-6 w-full flex-grow mt-4">
           
           {/* Term 1: Reconstruction */}
           <div className="flex-1 bg-slate-800 rounded-2xl shadow-lg border-t-4 border-blue-500 p-8 flex flex-col">
             <div className="flex justify-between items-start mb-6 border-b border-slate-700 pb-4">
               <div>
                 <h4 className="font-bold text-blue-400 text-xl">1. Reconstruction Term</h4>
                 <span className="text-[10px] font-mono text-slate-400 uppercase tracking-widest mt-1 block">Expected Log-Likelihood</span>
               </div>
               <Layers className="w-8 h-8 text-blue-500 opacity-50" />
             </div>
             
             <ul className="space-y-4 text-sm text-slate-300 flex-grow">
               <li className="flex gap-3">
                 <div className="w-1.5 h-1.5 bg-blue-500 rounded-full mt-1.5 shrink-0"></div>
                 <p>Measures how well the <strong>Decoder <span className="font-mono text-blue-400">p<sub className="text-[10px]">θ</sub>(x|z)</span></strong> reconstructs input <span className="font-mono">x</span> from latent sample <span className="font-mono">z</span>.</p>
               </li>
               <li className="flex gap-3">
                 <div className="w-1.5 h-1.5 bg-blue-500 rounded-full mt-1.5 shrink-0"></div>
                 <p>Maximizing this encourages the model to store exact, fine-grained details of the image in the latent space.</p>
               </li>
               <li className="flex gap-3">
                 <div className="w-1.5 h-1.5 bg-blue-500 rounded-full mt-1.5 shrink-0"></div>
                 <p>If <span className="font-mono text-blue-400">p<sub className="text-[10px]">θ</sub></span> is a Gaussian, this term mathematically simplifies into <strong>Mean Squared Error (MSE)</strong>. If Bernoulli, it becomes <strong>Binary Cross-Entropy</strong>.</p>
               </li>
             </ul>
           </div>

           {/* Term 2: Regularization */}
           <div className="flex-1 bg-slate-800 rounded-2xl shadow-lg border-t-4 border-rose-500 p-8 flex flex-col">
             <div className="flex justify-between items-start mb-6 border-b border-slate-700 pb-4">
               <div>
                 <h4 className="font-bold text-rose-400 text-xl">2. Regularization Term</h4>
                 <span className="text-[10px] font-mono text-slate-400 uppercase tracking-widest mt-1 block">KL Divergence to Prior</span>
               </div>
               <Split className="w-8 h-8 text-rose-500 opacity-50" />
             </div>
             
             <ul className="space-y-4 text-sm text-slate-300 flex-grow">
               <li className="flex gap-3">
                 <div className="w-1.5 h-1.5 bg-rose-500 rounded-full mt-1.5 shrink-0"></div>
                 <p>Measures how far the <strong>Encoder's guess <span className="font-mono text-rose-400">q<sub className="text-[10px]">φ</sub>(z|x)</span></strong> diverges from the simple chosen <strong>Prior <span className="font-mono text-rose-400">p(z)</span></strong> (usually <span className="font-mono">N(0, I)</span>).</p>
               </li>
               <li className="flex gap-3">
                 <div className="w-1.5 h-1.5 bg-rose-500 rounded-full mt-1.5 shrink-0"></div>
                 <p>It penalizes the Encoder if it tries to output overly complex distributions or points far away from the center (0,0).</p>
               </li>
               <li className="flex gap-3">
                 <div className="w-1.5 h-1.5 bg-rose-500 rounded-full mt-1.5 shrink-0"></div>
                 <p>Without this term, the latent space would shatter into isolated islands. This forces the latent space to be a dense, smooth sphere perfect for generation!</p>
               </li>
             </ul>
           </div>

        </div>
      </div>
    </div>
  );
};

// --- SLIDE 7: VAE Summary & Architecture ---
const VAESummarySlide = () => {
  const [activeFocus, setActiveFocus] = useState('encoder');

  const components = {
    encoder: {
      title: "1. The Encoder Network",
      formula: "q_φ(z|x)",
      desc: "Takes data x and outputs parameters for the distribution of z (e.g., mean and variance if Gaussian). Its learnable parameters are φ.",
      icon: <Network className="w-6 h-6 text-teal-400" />
    },
    decoder: {
      title: "2. The Decoder Network",
      formula: "p_θ(x|z)",
      desc: "Takes a latent sample z and outputs parameters for the distribution of x. Its learnable parameters are θ.",
      icon: <BrainCircuit className="w-6 h-6 text-blue-400" />
    },
    prior: {
      title: "3. The Chosen Prior",
      formula: "p(z)",
      desc: "A fixed distribution over latent variables, usually a Standard Multivariate Gaussian N(0,I).",
      icon: <Database className="w-6 h-6 text-purple-400" />
    }
  };

  return (
    <div className="flex flex-col h-full p-4 md:p-8 overflow-y-auto bg-slate-50">
      <h2 className="text-3xl font-bold text-slate-800 mb-2 text-center shrink-0">The Complete VAE Architecture</h2>
      <p className="text-slate-600 mb-6 text-center max-w-4xl mx-auto shrink-0 text-sm md:text-base">
        Let's summarize the pieces. A Variational Autoencoder consists of three core components working together to optimize the ELBO.
      </p>

      <div className="flex flex-col lg:flex-row gap-6 max-w-6xl mx-auto w-full flex-grow items-stretch pb-8">

        {/* Left: The 3 Components */}
        <div className="flex-1 flex flex-col gap-4">
           {Object.entries(components).map(([key, data]) => (
              <div
                key={key}
                onMouseEnter={() => setActiveFocus(key)}
                className={`p-5 rounded-2xl border-2 transition-all cursor-pointer flex gap-4 items-center ${activeFocus === key ? 'bg-white shadow-lg border-indigo-400 scale-[1.02]' : 'bg-slate-100 border-slate-200 opacity-70'}`}
              >
                 <div className="bg-slate-800 p-3 rounded-xl shadow-inner">{data.icon}</div>
                 <div>
                   <h3 className="font-bold text-slate-800">{data.title}</h3>
                   <div className="font-mono text-sm text-indigo-600 font-bold mb-1">{data.formula}</div>
                   <p className="text-xs text-slate-600 leading-relaxed">{data.desc}</p>
                 </div>
              </div>
           ))}
        </div>

        {/* Right: Training & Context */}
        <div className="flex-[1.2] flex flex-col gap-4">

           <div className="bg-slate-800 rounded-2xl shadow-xl border border-slate-700 p-6 flex flex-col text-white">
              <h3 className="text-lg font-bold text-emerald-400 mb-2 flex items-center gap-2 border-b border-slate-600 pb-2">
                <Target className="w-5 h-5"/> The Training Process
              </h3>
              <p className="text-sm text-slate-300 leading-relaxed mb-4">
                Training involves optimizing the ELBO <span className="font-mono bg-slate-700 px-1 rounded text-emerald-300">L(θ, φ; x)</span> with respect to both <span className="font-mono text-blue-400">θ</span> and <span className="font-mono text-teal-400">φ</span> using techniques like stochastic gradient ascent.
              </p>
              <div className="bg-slate-900 p-4 rounded-xl border border-slate-600 shadow-inner flex flex-col gap-2">
                 <span className="text-xs font-bold text-slate-400 uppercase tracking-widest text-center">The Balancing Act</span>
                 <div className="flex justify-between items-center text-sm font-mono font-bold">
                   <span className="text-blue-400">Data Reconstruction</span>
                   <span className="text-slate-500">⚖️</span>
                   <span className="text-rose-400">Latent Regularization</span>
                 </div>
                 <p className="text-[10px] text-slate-400 text-center mt-2">
                   This balance is what allows VAEs to learn rich, structured representations AND generate novel data samples.
                 </p>
              </div>
           </div>

           <div className="bg-indigo-50 border-2 border-indigo-200 rounded-2xl shadow-sm p-6 flex flex-col">
              <h3 className="text-lg font-bold text-indigo-900 mb-2 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-indigo-600"/> Why "Variational"?
              </h3>
              <p className="text-sm text-slate-700 leading-relaxed">
                The term <strong>Variational</strong> comes from the <em>Calculus of Variations</em>, where we optimize functionals (functions of functions). In this case, we are searching for the best possible approximate distribution <span className="font-mono font-bold text-indigo-600">q_φ(z|x)</span> within a whole family of distributions parameterized by <span className="font-mono font-bold text-teal-600">φ</span>.
              </p>
           </div>

           <div className="bg-emerald-50 border-2 border-emerald-200 rounded-2xl shadow-sm p-4 flex items-center gap-4 mt-auto">
              <BookOpen className="w-8 h-8 text-emerald-600 shrink-0" />
              <div>
                <h4 className="font-bold text-emerald-900 text-sm">Coming Up Next</h4>
                <p className="text-xs text-emerald-800">
                  In the subsequent sections, we will explore the practicalities of optimizing this (like the Reparameterization Trick) and the implications of this formulation!
                </p>
              </div>
           </div>

        </div>
      </div>
    </div>
  );
};


// --- MAIN SLIDESHOW COMPONENT ---
const Slideshow = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const slides = [
    TheGoalSlide,
    VariationalHackSlide,
    MathDerivationSlide,
    ELBOBlockDiagramSlide,
    ELBORewriteSlide,
    VAEObjectiveSlide,
    VAESummarySlide
  ];

  const nextSlide = () => setCurrentSlide((prev) => (prev + 1) % slides.length);
  const prevSlide = () => setCurrentSlide((prev) => (prev - 1 + slides.length) % slides.length);

  const CurrentSlideComponent = slides[currentSlide];

  return (
    <div className="flex flex-col h-screen bg-slate-200 font-sans">
      {/* Top Progress Bar */}
      <div className="w-full h-1.5 bg-slate-300">
        <motion.div
          className="h-full bg-indigo-600"
          initial={{ width: '0%' }}
          animate={{ width: `${((currentSlide + 1) / slides.length) * 100}%` }}
        />
      </div>

      {/* Main Content Area */}
      <div className="flex-grow overflow-hidden relative">
        <AnimatePresence mode='wait'>
          <motion.div
            key={currentSlide}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.2 }}
            className="h-full w-full absolute inset-0"
          >
            <CurrentSlideComponent />
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Bottom Navigation */}
      <div className="flex justify-between items-center p-4 md:p-6 bg-white border-t border-slate-300 z-10">
        <button
          onClick={prevSlide}
          className="p-3 rounded-full bg-slate-100 text-slate-600 disabled:opacity-30 disabled:cursor-not-allowed transition-colors hover:bg-slate-200"
          disabled={currentSlide === 0}
        >
          <ChevronLeft className="w-6 h-6"/>
        </button>
        
        <div className="flex space-x-2">
          {slides.map((_, i) => (
            <div
              key={i}
              className={`w-2.5 h-2.5 rounded-full transition-all ${i === currentSlide ? 'bg-indigo-600 scale-125' : 'bg-slate-300'}`}
            />
          ))}
        </div>
        
        <button
          onClick={nextSlide}
          className="p-3 rounded-full bg-indigo-600 text-white disabled:opacity-30 disabled:cursor-not-allowed transition-colors hover:bg-indigo-500"
          disabled={currentSlide === slides.length - 1}
        >
          <ChevronRight className="w-6 h-6"/>
        </button>
      </div>
    </div>
  );
};

export default function App() {
  return (
    <div className="App">
      <Slideshow />
    </div>
  );
}